
SCRIPT_NAME=${BASH_SOURCE[0]}
SCRIPT_DIR=`dirname ${SCRIPT_NAME}`

ORIGINAL_DIR=${PWD}
cd ${SCRIPT_DIR}
SCRIPT_DIR=`pwd`
cd ${ORIGINAL_DIR}

export MAIN_DIR=${SCRIPT_DIR}
export BUILD_REL_DIR=build
export PATH="${MAIN_DIR}/${BUILD_REL_DIR}:${PATH}"
export LD_LIBRARY_PATH="${MAIN_DIR}/${BUILD_REL_DIR}:${LD_LIBRARY_PATH}"
