
SCRIPT_NAME=${BASH_SOURCE[0]}
SCRIPT_DIR=`dirname ${SCRIPT_NAME}`
ORIGINAL_DIR=${PWD}
cd ${SCRIPT_DIR}
SCRIPT_DIR=`pwd`
cd ${ORIGINAL_DIR}

export PATH="${SCRIPT_DIR}:${PATH}"
export LD_LIBRARY_PATH="${SCRIPT_DIR}:${LD_LIBRARY_PATH}"
